version: '3.9'
services:
  ### Apache and PHP Container
  webserver:
    container_name: PHP-webServer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - mysql-db
  ### Mysql container
  mysql-db:
    image: mysql:8.0
    volumes:
      - ./olympia2024_16-01-24.sql:/docker-entrypoint-initdb.d/olympia2024_16-01-24.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: olympia2024
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

    ports:
      - "3306:3306"